#ifndef ENUM_EDITOR_KEY_H
#define ENUM_EDITOR_KEY_H

enum editorKey
{
  BACKSPACE = 127,
  ARROW_LEFT = 1000,
  ARROW_RIGHT,
  ARROW_UP,
  ARROW_DOWN,
  DEL_KEY,
  HOME_KEY,
  END_KEY,
  PAGE_UP,
  PAGE_DOWN
};

enum editorHighlight
{
  HIGHLIGHT_NORMAL = 0,
  HIGHLIGHT_COMMENT,
  HIGHLIGHT_MULTILINE_COMMENT,
  HIGHLIGHT_KEYWORD1,
  HIGHLIGHT_KEYWORD2,
  HIGHLIGHT_STRING,
  HIGHLIGHT_NUMBER,
  HIGHLIGHT_MATCH
};

#endif